[package]
name = "km"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.5"
open = "2.0.2"
rusqlite = { version = "0.26.3", features = ["bundled"] }
shellexpand = "2.1.0"
